repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.7.2
  hooks:
    - id: terraform_validate_no_variables
    - id: terraform_fmt
    - id: terraform_docs
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
- repo: git://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.5
  hooks:
    - id: remove-crlf
    - id: forbid-tabs
